blog/urls.py
# blog/urls
"""
此路径下的urls只用于blog相关的urls配置
需要在主程序的urls.py下用include方法导入当前urls配置

"""
from django.conf.urls import url
from django.contrib import admin
from blog import views

# 视图函数命名空间,告诉Django这个urls.py模块是属于blog应用的,避免多个名为index,detail的冲突
#
app_name = 'blog'
# url和函数关系
urlpatterns = [
    # url(地址路径,处理函数)
    # django正则会去掉协议 域名 端口号,然后开始正则
    url(r'^admin/', admin.site.urls),
    # 视图函数写法
    # url(r'^$',views.index,name='index'),
    # 转换类视图函数为视图函数 as_view()将类转换为视图函数
    url(r'^$',views.IndexView.as_view(),name='index'),
    # 先获取用户点击的post-id,捕获得到post/255/ ,再将捕获到的参数传到视图函数detail中
    # url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    # 详情 类视图函数写法  此pk由models/Post类中的获取绝对路径方法生成的,如pk=255对应文章的id   detail(request,255)
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    # 正则归档年月archives(request, year=2017, month=3)
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.archives,name='archives'),
    # 归档的 类视图函数写法
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),
    # 正则获取分类id,进入只有该类的全部文章页面
    # url(r'^category/(?P<pk>[0-9]+)/$',views.category,name='category'),
    # 分类的 类视图函数写法
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$',views.TagView.as_view(),name='tag'),
    # 简单搜索功能
    # url(r'^search/$', views.search, name='search'),
]

blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog.feeds import AllPostRssFeed

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    # 导入app中的urls配置 会拼接两个urls字符串 即主程序中的r'pro/'+应用中urls中的r'blog/' = 'pro/blog'
    # namespace和app_name用于跟blog/urls的app_name='blog'对应(django1.8版本需要)
    url(r'',include('blog.urls',namespace='blog',app_name='blog')),
    url(r'',include('comments.urls')),
    url(r'^all/rss/$',AllPostRssFeed(),name='rss'),
    # haystack搜索引擎
    url(r'^search/', include('haystack.urls')),
]

comments/urls.py
#!-*-coding:utf-8 -*-
from django.conf.urls import  url
from . import views


app_name = 'comments'
urlpatterns = [
    # 此处邮箱正则有bug
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$',views.post_comment,name='post_comment'),
]

blog/models.py
"""存放模型,继承自modles.Model
创建了3个模型(表),类别表 标签表 文章表
文章表中包含类别和标签属性,用foreignKey和manyToManyField关联这两个类别表和标签表
更新模型后 要在python manage.py 中更新
"""
from django.db import models
# django内置应用
from django.contrib.auth.models import User
# python_2_unicode_compatible 装饰器用于兼容 Python2
from django.utils.six import python_2_unicode_compatible
# 调用urls的获取路径的方法
from django.urls import reverse
# 调用markdown
import markdown
# 调用去除html文本中的html标签
from django.utils.html import strip_tags


# python2用unicode替代str方法
# 文章分类表
@python_2_unicode_compatible
class Category(models.Model):
    # 超出长度无法存入到数据库
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# 文章标签类表
@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# 文章内容表 在表中加入与其他表的公共关键字作为外键
@python_2_unicode_compatible
class Post(models.Model):

    # 实例化对象
    # 文章标题 CharField()默认不能为空
    title =models.CharField(max_length=70)
    # 文章正文  内容较长的文本用TextField()
    body =models.TextField()
    # 文章创建时间  存储时间字段用DateTimeField() 在shell里赋值为timezone.now()
    created_time =models.DateTimeField()
    # 文章最后修改时间
    modified_time =models.DateTimeField()
    # 文章摘要  CharField默认不允许为空,改为允许空值
    excerpt =models.CharField(max_length=200,blank=True)
    # 实例化分类(一篇文章只能有一个分类 一对多用ForeignKey()) 不为空
    # 外键在django2.0后改为user=models.OneToOneField(User,on_delete=models.CASCADE)
    category =models.ForeignKey(Category)
    # 实例化标签(一篇文章可有多个标签,一个标签也可对应多个文章,多对多用ManyToManyField())
    tags =models.ManyToManyField(Tag,blank=True)
    # 作者  使用django内置应用
    author =models.ForeignKey(User)
    # 阅读量
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    # 自定义排序,在视图函数中就不用排序了
    class Meta:
        ordering = ['-created_time']

    """ 1.reverse的'blog:detail'对应blog应用下的name='detail'的方法(对应urls.py的name)
        2.reverse()方法会去解析'blog:detail'的url,解析规则是根据urls.py里的正则.
        3.根据正则规则,解析结果为post/255/,这样Post自己就生成了自己的url
        4.kwargs表示按照关键字传值将多余的传值用字典形式呈现
    """
    # 自定义获取路径方法
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    # 阅读量增加(粗略统计,同时访问被忽略)
    def increase_views(self):
        # 该函数每被调用一次 views+1
        self.views +=1
        # 只更新数据库中views字段的值
        self.save(update_fields=['views'])

    # 摘要逻辑 重写save()方法,保存到数据库之前进行一次过滤
    def save(self, *args, **kwargs):
        # 如果没填写摘要
        if not self.excerpt:
            # 实例化一个Markdown对象,用于渲染body的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        # 调用父类的 save 方法将数据保存到数据库中
        # 这里save不能有self参数(不能在模型保存中强制更新和插入)
        super(Post,self).save(*args, **kwargs)
    """或者可用模板过滤器(filter) 
    例如:<p> {{ post.body|truncatechars:54 }} </p>
    # 将会显示文章内容的前54个字节,若文章前54字节包含html标签,仍将作为摘要会显示
    """

comments/models.py
"""评论模块 模型"""
from django.db import models
from django.utils.six import python_2_unicode_compatible

@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    # 创建评论时间为当前系统时间,应改为utc/网络 时间
    created_time = models.DateTimeField(auto_now_add=True)
    # 一篇文章可有多个评论(用外键)
    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blog/views.py
import markdown

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post, Category, Tag
# 引入markdown
import markdown
# 引入评论CommentForm
from comments.forms import CommentForm
# django 的类视图函数写法
from django.views.generic import ListView,DetailView
# 美化锚点链接的url
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
# 搜索功能
from django.db.models import Q

# def index(request):
    # return HttpResponse("欢迎访问我的博客首页!")
    # render(request,模板名,context={})
    # 逆序排序获得全部文章
    # post_list=Post.objects.all().order_by('-created_time')
    # return render(request,'blog/index.html',context={
    # # title welcome 对应模板里的{{title}} {{welcome}}
        # 'title':'我的博客首页',
        # 'welcome':'欢迎访问我的博客首页',
        # 'post_list':post_list
    # })


# 首页视图函数def
# def index(request):
#     post_list = Post.objects.all().order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})

# 简单搜索
def search(request):
    # 获取模板中name='q' 即用户搜索的关键词
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = "请输入关键字"
        return render(request,'blog/index.html',{'error_msg':error_msg})
    # 过滤器:要过滤的属性title和body + __ +i前缀(不区分大小写) + contains(包含)
    # 用Q对象和| 实现或效果
    #如果不用 Q 对象,就只能写成title__icontains=q,body__icontains=q,这是且关系
    post_list = Post.objects.filter(Q(title__icontains=q)|Q(body__icontains=q))
    return render(request,'blog/index.html',{'error_msg':error_msg,
                                             'post_list':post_list})


"""首页视图(django类视图函数写法)
 继承某个类视图,ListView用于从数据库获取模型列表数据,所以此处继承ListView
 之后在urls中将该类转换为视图函数def
"""
class IndexView(ListView):
    # 告诉ListView我们要获取的模型是Post
    model = Post
    # 指定这个视图渲染的模板
    template_name = 'blog/index.html'
    # 获取到的列表数据保存到这个变量名中
    context_object_name = 'post_list'
    # 激活分页 如:每页显示2条博客
    paginate_by = 2

    def get_queryset(self):
        return super(IndexView,self).get_queryset().order_by('-created_time')

    # 详细分页
    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)

        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data

# 详情视图
# def detail(request,pk):
#     # 调用系统方法,有就正常返回,没有则404
#     post=get_object_or_404(Post,pk=pk)
#     # 阅读量+1
#     post.increase_views()
#     '''
#     允许markdown:
#     1.install markdown和pygments
#     2.django过滤器设置,模板中{{post.body|safe}}
#     3.引入高亮css
#     4.编写逻辑:渲染html再传递给模板
#     文章存在post.body中,对其进行markdown渲染后再传递给模板
#     说明:extra包含很多扩展,codehilite语法高亮提示,toc允许生成目录
#     '''
#     post.body = markdown.markdown(post.body,
#                                   extensions=[
#                                      'markdown.extensions.extra',
#                                      'markdown.extensions.codehilite',
#                                      'markdown.extensions.toc',
#                                   ])
#     form = CommentForm()
#     # 获取这篇post下的全部评论
#     comment_list = post.comment_set.all()
#     # 将文章/表单/评论列表作为模板变量传给detail.html模板
#     context = {'post':post,
#                'form':form,
#                'comment_list':comment_list}
#     return  render(request,'blog/detail.html',context=context)
#     # return render(request, 'blog/detail.html', context={'post': post})

# 详情视图的 类视图函数写法
class PostDetailView(DetailView):
    model=Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'
    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView,self).get(request,*args,**kwargs)
        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()
       # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        # post = super(PostDetailView, self).get_object(queryset=None)
        # post.body = markdown.markdown(post.body,
        #                               extensions=[
        #                                   'markdown.extensions.extra',
        #                                   'markdown.extensions.codehilite',  # 高亮拓展
        #                                   'markdown.extensions.toc',  # 目录拓展
        #                               ])
        # 用markdown渲染文章目录侧边栏
        post = super(PostDetailView, self).get_object(queryset=None)
        # 先创建一个markdown.Markdown的实例化对象
        """
        和之前不同的是，extensions中的toc拓展不再是字符串markdown.extensions.toc ，
        而是TocExtension的实例.TocExtension在实例化时其slugify参数可以接受一个函数作为参数，
        这个函数将被用于处理标题的锚点值。Markdown 内置的处理方法不能处理中文标题，
        所以我们使用了 django.utils.text 中的 slugify 方法，该方法可以很好地处理中文。
        """
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            # 'markdown.extensions.toc',
            # 让markdown锚点可处理中文
            TocExtension(slugify=slugify)
        ])
        # 使用该实例的convert方法将post.body中的Markdown文本渲染成HTML文本
        post.body = md.convert(post.body)
        """
        而一旦调用该方法后，实例 md 就会多出一个 toc 属性，这个属性的值就是内容的目录，
        我们把 md.toc 的值赋给 post.toc 属性（要注意这个 post 实例本身是没有 md 属性的，
        我们给它动态添加了 md 属性，这就是 Python 动态语言的好处，
        不然这里还真不知道该怎么把 toc 的值传给模板
        """
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
        # 还要把评论表单、post 下的评论列表传递给模板。
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                            <span class="views-count">
                                <a href="#">标签:
                                {% for tag in post.tags.all %}
                                    {{ tag.name }}
                                {% endfor %}
                                </a>
                            </span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.body|safe }}
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <!-- 表单 -->
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                <!-- 会自动渲染出input标签
                                 form.xxx.errors:例如用户email格式填错了,那么Django会检查用户提交的email的格式,
                                 然后将格式错误信息保存到 errors 中，模板便将错误信息渲染显示。

                                 -->
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ form.text.id_for_label }}">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                        <!-- 显示所有真实评论 -->
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date">{{ comment.created_time }}"</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            暂无评论
                            {% endfor %}
                        </ul>
                    </div>
                </section>
{% endblock main %}
<!-- 文章目录侧边栏 -->
{% block toc %}
{#            <aside class="col-md-4">#}
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    <!-- 使用 safe 标签防止 Django 对其转义 -->
                    {{ post.toc|safe }}
                </div>
{#            </aside>#}
{% endblock toc %}

templates/blog/index.html
{# 模板继承 #}
{% extends 'base.html' %}
{% block main %}
    <!-- 搜索信息 -->
    {% if error_msg %}
    <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        {# post.pk为post对应数据库中的id值   #}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
                    <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                    <span class="views-count">
                                <a href="#">标签:
                                    {% for tag in post.tags.all %}
                                        {{ tag.name }}
                                    {% endfor %}
                                </a>
                            </span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>摘要:{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {# 当post_list为空时显示empty下面的内容       #}
    {% empty %}
        <div class="no-post">暂时还没有发布的文章!</div>
    {% endfor %}

    <!-- 简单分页效果 -->
    {#                {% if is_paginated %}#}
    {#                <div class="pagination-simple">#}
    {#                    <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->#}
    {#                    {% if page_obj.has_previous %}#}
    {#                    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>#}
    {#                    {% endif %}#}
    {#                    <!-- 显示当前页面信息 -->#}
    {#                    <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>#}
    {#                    <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->#}
    {#                    {% if page_obj.has_next %}#}
    {#                    <a href="?page={{ page_obj.next_page_number }}">下一页</a>#}
    {#                    {% endif %}#}
    {#                </div>#}
    {#                {% endif %}#}

    <!-- 详细分页 -->
    {% if is_paginated %}
        <div class="pagination">
            {% if first %}
                <a href="?page=1">1</a>
            {% endif %}
            {% if left %}
                {% if left_has_more %}
                    <span>...</span>
                {% endif %}
                {% for i in left %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
            {% endif %}
            <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
            {% if right %}
                {% for i in right %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
                {% if right_has_more %}
                    <span>...</span>
                {% endif %}
            {% endif %}
            {% if last %}
                <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
            {% endif %}
        </div>
    {% endif %}
{% endblock main %}