blog/urls.py
# blog/urls
"""
此路径下的urls只用于blog相关的urls配置
需要在主程序的urls.py下用include方法导入当前urls配置

"""
from django.conf.urls import url
from django.contrib import admin
from blog import views

# 视图函数命名空间,告诉Django这个urls.py模块是属于blog应用的,避免多个名为index,detail的冲突
#
app_name = 'blog'
# url和函数关系
urlpatterns = [
    # url(地址路径,处理函数)
    # django正则会去掉协议 域名 端口号,然后开始正则
    url(r'^admin/', admin.site.urls),
    # 视图函数写法
    # url(r'^$',views.index,name='index'),
    # 转换类视图函数为视图函数 as_view()将类转换为视图函数
    url(r'^$',views.IndexView.as_view(),name='index'),
    # 先获取用户点击的post-id,捕获得到post/255/ ,再将捕获到的参数传到视图函数detail中
    # url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    # 详情 类视图函数写法  此pk由models/Post类中的获取绝对路径方法生成的,如pk=255对应文章的id   detail(request,255)
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    # 正则归档年月archives(request, year=2017, month=3)
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.archives,name='archives'),
    # 归档的 类视图函数写法
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),
    # 正则获取分类id,进入只有该类的全部文章页面
    # url(r'^category/(?P<pk>[0-9]+)/$',views.category,name='category'),
    # 分类的 类视图函数写法
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$',views.TagView.as_view(),name='tag'),
    # 简单搜索功能
    # url(r'^search/$', views.search, name='search'),
]

blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog.feeds import AllPostRssFeed

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    # 导入app中的urls配置 会拼接两个urls字符串 即主程序中的r'pro/'+应用中urls中的r'blog/' = 'pro/blog'
    # namespace和app_name用于跟blog/urls的app_name='blog'对应(django1.8版本需要)
    url(r'',include('blog.urls',namespace='blog',app_name='blog')),
    url(r'',include('comments.urls')),
    url(r'^all/rss/$',AllPostRssFeed(),name='rss'),
    # haystack搜索引擎
    url(r'^search/', include('haystack.urls')),
]

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <!-- 引入搭配markdown的语法高亮css -->
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

    <style>
        span.highlighted {
            color: red;
        }
    </style>
    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

</head>

<body>
<div class="container">
    <!-- 上方导航栏-->
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                 {# <h1><a href="index.html"><b>Black</b> &amp; White</a></h1> #}
                    <h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页123模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>
<!-- 内容 -->
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <!-- 侧面栏 -->
            <aside class="col-md-4">
                <!-- 文章目录(固定死无逻辑)-->
               {% block toc %}
               {% endblock toc %}
                <!-- 最新文章 -->
                <!-- 将最近的5条文章列表用as保存到recent_post_list模板变量中 -->
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>
                        {% empty %}
                            暂无文章！
                        {% endfor %}
                    </ul>
                </div>
                <!-- 按月归档 -->
                <!-- date格式对象自带year month等属性 -->
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
{#                模板标签 archives 位于templatetags中#}
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                            <li>
{#                                链接到 blog项目的name=archives的url#}
                                <a href="{% url 'blog:archives' date.year date.month %}">
                                    {{ date.year }} 年 {{ date.month }} 月
                                </a>
                            </li>
                        {% empty %}
                            暂无归档！
                        {% endfor %}
                    </ul>
                </div>
                <!-- 文章分类 -->
                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <!-- 显示该分类下的文章数目 -->
                                <a href="{% url 'blog:category' category.pk %}">
                                    {{ category.name }} <span class="post-count">({{ category.num_posts }})</span>
                                </a>
                            </li>
                        {% empty %}
                            暂无分类！
                        {% endfor %}
                    </ul>
                </div>
                <!-- 文章标签云 -->
               <div class="widget widget-tag-cloud">
                   <h3 class="widget-title">标签云</h3>
                   {% get_tags as tag_list %}
                   <ul>
                     {% for tag in tag_list %}
                     <li>
                       <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                     </li>
                     {% empty %}
                     暂无标签！
                     {% endfor %}
                   </ul>
                </div>
                <!-- rss订阅 -->
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<!-- 底部-->
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2018 - github<a href="http://www.github.com/"
                                                        target="_blank" title="github">github</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>